---
title: "Problem 6.3"
author: "Chen Bo Calvin Zhang"
date: "09/11/2020"
output: pdf_document
---

Import and preprocess the data

```{r, echo=TRUE}
data(iris)

# preprocess
X.iris = scale((iris[, 1:4]), scale=TRUE) # center and standardise
L.iris = iris[, 5]

table(L.iris)

pairs(X.iris, col=as.integer(L.iris), pch=as.integer(L.iris)+14)
```

Now, perform K-means with K = 3.

```{r, echo=TRUE}
kmeans.out3 = kmeans(X.iris, centers = 3)
kmeans.out3
```

And plot the clusters obtained with K-means.

```{r, echo=TRUE}
plot(X.iris, col = kmeans.out3$cluster, pch = as.integer(L.iris) + 14, main = "K-Means")
```

Compare the predicted clusters with the original ones.

```{r, echo=TRUE}
table(L.iris, kmeans.out3$cluster)
```

Let us apply K-means with varying values of K and check the between group and within group variation.

```{r, echo=TRUE}
between_var = numeric(10)
within_var = numeric(10)

for (k in 1:10)
{
  kmeans.out = kmeans(X.iris, centers = k)
  between_var[k] = kmeans.out$betweenss
  within_var[k] = kmeans.out$tot.withinss
}
```

Lastly, let us plot the variations.

```{r, echo=TRUE}
plot(1:10, between_var, ylim = c(0, max(c(max(between_var, within_var)))),
     type = "b", xlab = "K", ylab = "Variation", main = "K-means Iris Data")
points(1:10, within_var, type = "b", col = 2, pch = 2)
legend("right", c("Between SS (explained)", "Within SS (unexplained)"),
       col=c(1,2), pch=c(1,2))
```